import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { buildChart, resample, CHARTS } from "./trace.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(HERE, "../../../lib/pa28-181-climbdescent.ts");

const round = (v, p) => Number(v.toFixed(p));

function chartData(pageNo) {
  const { spec, fam, panels } = buildChart(pageNo);
  return {
    figure: spec.figure,
    phase: spec.phase,
    // Neither figure draws sea level as its own curve — it runs along the plot's
    // bottom rule. That rule sits one family step below the 1,000 ft curve on
    // both charts, so using it as the sea-level line is what the page shows.
    seaLevel: round(spec.box.bottom, 1),
    altitudes: fam.map(c => ({
      alt: c.alt,
      // (OAT °C, shared coordinate) along the curve, evenly sampled.
      curve: resample(c.oats, c.pys, 21).map(([o, y]) => [round(o, 2), round(y, 1)]),
    })).sort((a, b) => a.alt - b.alt),
    panels: Object.fromEntries(panels.map(p => [
      p.key,
      resample(p.ys, p.vals, 61).map(([y, v]) => [round(y, 1), round(v, 3)]),
    ])),
  };
}

const charts = [chartData(163), chartData(174)];

const body = `// Generated by scripts/pohtrace/climbdescent/export.mjs — do not edit by hand.
//
// Figures 5-17 and 5-37 of the PA-28-181 POH (Piper VB-2960, 16 November 2020),
// digitised from the POH's raster pages.
//
// Each chart is a nomogram read in one pass: enter at the outside air
// temperature, go up to the pressure altitude curve, across to each panel
// curve, and down to the value. The horizontal leg is what ties the four
// together, so every curve here is expressed against that shared coordinate —
// \`curve\` gives it for an (OAT, pressure altitude) entry point, and \`panels\`
// turns it back into minutes, gallons and nautical miles. The coordinate itself
// is in page pixels and means nothing outside this file.
//
// Checked against each chart's own printed construction lines: on 5-17 the
// cruise entry lands within half a pixel of the line Piper drew, and time and
// fuel read back exactly. Piper's printed answers are those same readings
// rounded to whole units.

export interface AltitudeCurve {
  /** Pressure altitude, feet. */
  alt: number;
  /** [outside air temperature °C, shared coordinate] along the curve. */
  curve: [number, number][];
}

export interface ChartData {
  figure: string;
  phase: "climb" | "descent";
  /** The shared coordinate of the sea-level line. */
  seaLevel: number;
  /** Lowest drawn altitude first; sea level is held separately, above. */
  altitudes: AltitudeCurve[];
  /** [shared coordinate, value] for each panel. */
  panels: {
    timeMin: [number, number][];
    fuelGal: [number, number][];
    distanceNm: [number, number][];
  };
}

export const CLIMB_DATA: ChartData = ${JSON.stringify(charts[0], null, 2)} as ChartData;

export const DESCENT_DATA: ChartData = ${JSON.stringify(charts[1], null, 2)} as ChartData;
`;

fs.writeFileSync(OUT, body);
console.log(`wrote ${path.relative(process.cwd(), OUT)}`);
for (const c of charts) {
  console.log(`  ${c.figure} (${c.phase}): ${c.altitudes.length} altitude curves, ` +
    `${c.altitudes[0].alt}–${c.altitudes.at(-1).alt} ft`);
}
