// Generated by scripts/pohtrace/cruise/extract.mjs — do not edit by hand.
//
// Figures 5-21, 5-23 and 5-25 of the PA-28-181 POH (Piper VB-2960, 16 November
// 2020): engine and cruise performance at 55%, 65% and 75% power, best economy
// mixture, 2,550 lb.
//
// These three figures are tables and the PDF carries a text layer for them, so
// unlike the graph digitisations elsewhere in this app these numbers are Piper's
// own — read out of the file, not measured off a scan. Every row is checked on
// extraction against two identities printed in the table itself: °F against °C,
// and the stated ISA deviation against the standard lapse rate.
//
// True airspeed is printed only at the coldest and warmest row of each altitude
// block, which is how Piper set it — at constant power it barely moves with
// temperature, so they gave the two ends and left the middle to the eye.

export interface CruiseRow {
  /** Deviation from standard temperature, °C. */
  isaDev: number;
  oatC: number;
  oatF: number;
  rpm: number;
  /** Knots true airspeed, where the table prints it. */
  ktas: number | null;
}

export interface CruiseAltitude {
  /** Pressure altitude, feet. */
  alt: number;
  rows: CruiseRow[];
}

export interface CruiseTable {
  figure: string;
  /** Percentage of rated power. */
  power: number;
  /** Best economy mixture fuel flow, US gallons per hour. */
  gph: number;
  altitudes: CruiseAltitude[];
}

export const CRUISE_TABLES: CruiseTable[] = [
  {
    "figure": "5-21",
    "power": 55,
    "gph": 8.2,
    "altitudes": [
      {
        "alt": 0,
        "rows": [
          {
            "isaDev": -15,
            "oatC": 0,
            "oatF": 32,
            "rpm": 2245,
            "ktas": 102
          },
          {
            "isaDev": 0,
            "oatC": 15,
            "oatF": 59,
            "rpm": 2265,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 25,
            "oatF": 77,
            "rpm": 2275,
            "ktas": null
          },
          {
            "isaDev": 20,
            "oatC": 35,
            "oatF": 95,
            "rpm": 2285,
            "ktas": null
          },
          {
            "isaDev": 30,
            "oatC": 45,
            "oatF": 113,
            "rpm": 2295,
            "ktas": 103
          }
        ]
      },
      {
        "alt": 2000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -4,
            "oatF": 25,
            "rpm": 2265,
            "ktas": 103
          },
          {
            "isaDev": 0,
            "oatC": 11,
            "oatF": 52,
            "rpm": 2280,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 21,
            "oatF": 70,
            "rpm": 2295,
            "ktas": null
          },
          {
            "isaDev": 20,
            "oatC": 31,
            "oatF": 88,
            "rpm": 2305,
            "ktas": null
          },
          {
            "isaDev": 30,
            "oatC": 41,
            "oatF": 106,
            "rpm": 2315,
            "ktas": 104
          }
        ]
      },
      {
        "alt": 4000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -8,
            "oatF": 18,
            "rpm": 2285,
            "ktas": 103
          },
          {
            "isaDev": 0,
            "oatC": 7,
            "oatF": 45,
            "rpm": 2300,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 17,
            "oatF": 63,
            "rpm": 2315,
            "ktas": null
          },
          {
            "isaDev": 20,
            "oatC": 27,
            "oatF": 81,
            "rpm": 2325,
            "ktas": null
          },
          {
            "isaDev": 30,
            "oatC": 37,
            "oatF": 99,
            "rpm": 2335,
            "ktas": 105
          }
        ]
      },
      {
        "alt": 6000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -12,
            "oatF": 10,
            "rpm": 2305,
            "ktas": 104
          },
          {
            "isaDev": 0,
            "oatC": 3,
            "oatF": 37,
            "rpm": 2320,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 13,
            "oatF": 55,
            "rpm": 2330,
            "ktas": null
          },
          {
            "isaDev": 20,
            "oatC": 23,
            "oatF": 73,
            "rpm": 2345,
            "ktas": null
          },
          {
            "isaDev": 30,
            "oatC": 33,
            "oatF": 91,
            "rpm": 2355,
            "ktas": 105
          }
        ]
      },
      {
        "alt": 8000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -16,
            "oatF": 3,
            "rpm": 2320,
            "ktas": 104
          },
          {
            "isaDev": 0,
            "oatC": -1,
            "oatF": 30,
            "rpm": 2340,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 9,
            "oatF": 48,
            "rpm": 2350,
            "ktas": null
          },
          {
            "isaDev": 17.5,
            "oatC": 16.5,
            "oatF": 62,
            "rpm": 2360,
            "ktas": 105
          }
        ]
      },
      {
        "alt": 9000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -18,
            "oatF": 0,
            "rpm": 2330,
            "ktas": 104
          },
          {
            "isaDev": 0,
            "oatC": -3,
            "oatF": 27,
            "rpm": 2350,
            "ktas": null
          },
          {
            "isaDev": 8.5,
            "oatC": 5.5,
            "oatF": 42,
            "rpm": 2360,
            "ktas": 105
          }
        ]
      },
      {
        "alt": 10000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -20,
            "oatF": -4,
            "rpm": 2340,
            "ktas": 104
          },
          {
            "isaDev": 0,
            "oatC": -5,
            "oatF": 23,
            "rpm": 2360,
            "ktas": 105
          }
        ]
      }
    ]
  },
  {
    "figure": "5-23",
    "power": 65,
    "gph": 9.5,
    "altitudes": [
      {
        "alt": 0,
        "rows": [
          {
            "isaDev": -15,
            "oatC": 0,
            "oatF": 32,
            "rpm": 2385,
            "ktas": 110
          },
          {
            "isaDev": 0,
            "oatC": 15,
            "oatF": 59,
            "rpm": 2405,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 25,
            "oatF": 77,
            "rpm": 2415,
            "ktas": null
          },
          {
            "isaDev": 20,
            "oatC": 35,
            "oatF": 95,
            "rpm": 2430,
            "ktas": null
          },
          {
            "isaDev": 30,
            "oatC": 45,
            "oatF": 113,
            "rpm": 2440,
            "ktas": 113
          }
        ]
      },
      {
        "alt": 2000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -4,
            "oatF": 25,
            "rpm": 2405,
            "ktas": 111
          },
          {
            "isaDev": 0,
            "oatC": 11,
            "oatF": 52,
            "rpm": 2425,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 21,
            "oatF": 70,
            "rpm": 2440,
            "ktas": null
          },
          {
            "isaDev": 20,
            "oatC": 31,
            "oatF": 88,
            "rpm": 2450,
            "ktas": null
          },
          {
            "isaDev": 30,
            "oatC": 41,
            "oatF": 106,
            "rpm": 2465,
            "ktas": 114
          }
        ]
      },
      {
        "alt": 4000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -8,
            "oatF": 18,
            "rpm": 2430,
            "ktas": 112
          },
          {
            "isaDev": 0,
            "oatC": 7,
            "oatF": 45,
            "rpm": 2450,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 17,
            "oatF": 63,
            "rpm": 2460,
            "ktas": null
          },
          {
            "isaDev": 20,
            "oatC": 27,
            "oatF": 81,
            "rpm": 2475,
            "ktas": null
          },
          {
            "isaDev": 30,
            "oatC": 37,
            "oatF": 99,
            "rpm": 2485,
            "ktas": 115
          }
        ]
      },
      {
        "alt": 6000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -12,
            "oatF": 10,
            "rpm": 2450,
            "ktas": 113
          },
          {
            "isaDev": 0,
            "oatC": 3,
            "oatF": 37,
            "rpm": 2470,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 13,
            "oatF": 55,
            "rpm": 2485,
            "ktas": null
          },
          {
            "isaDev": 20,
            "oatC": 23,
            "oatF": 73,
            "rpm": 2495,
            "ktas": null
          },
          {
            "isaDev": 30,
            "oatC": 33,
            "oatF": 91,
            "rpm": 2510,
            "ktas": 116
          }
        ]
      },
      {
        "alt": 8000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -16,
            "oatF": 3,
            "rpm": 2475,
            "ktas": 114
          },
          {
            "isaDev": 0,
            "oatC": -1,
            "oatF": 30,
            "rpm": 2495,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 9,
            "oatF": 48,
            "rpm": 2505,
            "ktas": null
          },
          {
            "isaDev": 17.5,
            "oatC": 16.5,
            "oatF": 62,
            "rpm": 2515,
            "ktas": 116
          }
        ]
      },
      {
        "alt": 9000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -18,
            "oatF": 0,
            "rpm": 2485,
            "ktas": 114
          },
          {
            "isaDev": 0,
            "oatC": -3,
            "oatF": 27,
            "rpm": 2505,
            "ktas": null
          },
          {
            "isaDev": 8.5,
            "oatC": 5.5,
            "oatF": 42,
            "rpm": 2515,
            "ktas": 116
          }
        ]
      },
      {
        "alt": 10000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -20,
            "oatF": -4,
            "rpm": 2495,
            "ktas": 115
          },
          {
            "isaDev": 0,
            "oatC": -5,
            "oatF": 23,
            "rpm": 2515,
            "ktas": 116
          }
        ]
      }
    ]
  },
  {
    "figure": "5-25",
    "power": 75,
    "gph": 11,
    "altitudes": [
      {
        "alt": 0,
        "rows": [
          {
            "isaDev": -15,
            "oatC": 0,
            "oatF": 32,
            "rpm": 2485,
            "ktas": 116
          },
          {
            "isaDev": 0,
            "oatC": 15,
            "oatF": 59,
            "rpm": 2515,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 25,
            "oatF": 77,
            "rpm": 2535,
            "ktas": null
          },
          {
            "isaDev": 20,
            "oatC": 35,
            "oatF": 95,
            "rpm": 2550,
            "ktas": null
          },
          {
            "isaDev": 30,
            "oatC": 45,
            "oatF": 113,
            "rpm": 2565,
            "ktas": 121
          }
        ]
      },
      {
        "alt": 2000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -4,
            "oatF": 25,
            "rpm": 2520,
            "ktas": 118
          },
          {
            "isaDev": 0,
            "oatC": 11,
            "oatF": 52,
            "rpm": 2545,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 21,
            "oatF": 70,
            "rpm": 2565,
            "ktas": null
          },
          {
            "isaDev": 20,
            "oatC": 31,
            "oatF": 88,
            "rpm": 2580,
            "ktas": null
          },
          {
            "isaDev": 30,
            "oatC": 41,
            "oatF": 106,
            "rpm": 2600,
            "ktas": 123
          }
        ]
      },
      {
        "alt": 3000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -6,
            "oatF": 21,
            "rpm": 2535,
            "ktas": 119
          },
          {
            "isaDev": 0,
            "oatC": 9,
            "oatF": 48,
            "rpm": 2560,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 19,
            "oatF": 66,
            "rpm": 2580,
            "ktas": null
          },
          {
            "isaDev": 20,
            "oatC": 29,
            "oatF": 84,
            "rpm": 2595,
            "ktas": null
          },
          {
            "isaDev": 30,
            "oatC": 39,
            "oatF": 102,
            "rpm": 2615,
            "ktas": 124
          }
        ]
      },
      {
        "alt": 4000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -8,
            "oatF": 18,
            "rpm": 2550,
            "ktas": 120
          },
          {
            "isaDev": 0,
            "oatC": 7,
            "oatF": 45,
            "rpm": 2575,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 17,
            "oatF": 63,
            "rpm": 2595,
            "ktas": null
          },
          {
            "isaDev": 20,
            "oatC": 27,
            "oatF": 81,
            "rpm": 2610,
            "ktas": null
          },
          {
            "isaDev": 30,
            "oatC": 37,
            "oatF": 99,
            "rpm": 2630,
            "ktas": 125
          }
        ]
      },
      {
        "alt": 5000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -10,
            "oatF": 14,
            "rpm": 2565,
            "ktas": 121
          },
          {
            "isaDev": 0,
            "oatC": 5,
            "oatF": 41,
            "rpm": 2590,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 15,
            "oatF": 59,
            "rpm": 2610,
            "ktas": null
          },
          {
            "isaDev": 20,
            "oatC": 25,
            "oatF": 77,
            "rpm": 2625,
            "ktas": null
          },
          {
            "isaDev": 25,
            "oatC": 30,
            "oatF": 86,
            "rpm": 2635,
            "ktas": 125
          }
        ]
      },
      {
        "alt": 6000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -12,
            "oatF": 10,
            "rpm": 2580,
            "ktas": 122
          },
          {
            "isaDev": 0,
            "oatC": 3,
            "oatF": 37,
            "rpm": 2605,
            "ktas": null
          },
          {
            "isaDev": 10,
            "oatC": 13,
            "oatF": 55,
            "rpm": 2625,
            "ktas": null
          },
          {
            "isaDev": 15,
            "oatC": 18,
            "oatF": 64,
            "rpm": 2635,
            "ktas": 125
          }
        ]
      },
      {
        "alt": 7000,
        "rows": [
          {
            "isaDev": -15,
            "oatC": -14,
            "oatF": 6.8,
            "rpm": 2595,
            "ktas": 123
          },
          {
            "isaDev": 0,
            "oatC": 1,
            "oatF": 34,
            "rpm": 2625,
            "ktas": null
          },
          {
            "isaDev": 7.5,
            "oatC": 8.5,
            "oatF": 47,
            "rpm": 2635,
            "ktas": 125
          }
        ]
      }
    ]
  }
];
